nota1 = int(input('Digite um número: '))
nota2 = int(input('Digite outro número: '))
print (f'{nota1} + {nota2} = {nota1+nota2}')
print (f'{nota1} - {nota2} = {nota1-nota2}')
print (f'{nota1} * {nota2} = {nota1*nota2}')
print (f'{nota1} / {nota2} = {nota1/nota2}')